<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.0.1" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="FluentValidation" Version="12.0.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
        <PackageReference Include="HRS.Shared.Core" Version="0.1.5" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
        <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
        <PackageReference Include="Stripe.net" Version="49.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HRS.Infrastructure\HRS.Infrastructure.csproj" />
        <ProjectReference Include="..\HRS.Domain\HRS.Domain.csproj" />
        <ProjectReference Include="..\HRS.Migrations\HRS.Migrations.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Contracts\DTOs\Auth\" />
      <Folder Include="Contracts\DTOs\Availability\" />
      <Folder Include="Contracts\DTOs\Catalog\" />
      <Folder Include="Contracts\DTOs\Item\" />
      <Folder Include="Contracts\DTOs\Package\" />
      <Folder Include="Contracts\DTOs\Payment\" />
      <Folder Include="Contracts\DTOs\RentalOrder\" />
      <Folder Include="Contracts\DTOs\User\" />
      <Folder Include="Models\" />
      <Folder Include="Services\Helpers\" />
      <Folder Include="Validators\Auth\" />
      <Folder Include="Validators\Item\" />
      <Folder Include="Validators\Package\" />
      <Folder Include="Validators\Payment\" />
      <Folder Include="Validators\RentalOrder\" />
      <Folder Include="Validators\User\" />
    </ItemGroup>

</Project>
